config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#top'
  get '/home/about' => 'home#about', as: 'about'
  get '/users/quit' => 'users#quit', as: 'quit'
  get '/fish' => 'fishing_parks#fish'


  resources :fishing_parks do
    get :fish, on: :member
    get :rank, on: :collection
    get :search, on: :collection
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :destroy, :update]
  resource :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_park
  
  validates_uniqueness_of :fishing_park_id, scope: :user_id
  
end

app/models/fishing_park.rb
class FishingPark < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy

  has_many :reviews, dependent: :destroy


  attachment :image
  attachment :map_image


  def self.search(word)
    # return FishingPark.all unless search
    FishingPark.where(['name LIKE ?', "%#{word}%"])
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_park
  
  # 評価を必須にする
  validates :score, presence: true
  validates :content, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fishing_parks, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

  def favorited_by?(fishing_park_id)
   favorites.where(fishing_park_id: fishing_park_id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    fishing_parks_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])

    devise_parameter_sanitizer.permit(:account_update,keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_fishing

  def create
    @favorite = Favorite.create(user_id: current_user.id, fishing_park_id: params[:fishing_park_id])
    # 非同期通信を行うためコメントアウト
    # redirect_to fishing_park_path(params[:fishing_park_id])
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, fishing_park_id: params[:fishing_park_id])
    @favorite.destroy
    # 非同期通信を行うためコメントアウト
    # redirect_to fishing_park_path(params[:fishing_park_id])
  end

  private
  def set_fishing
    @fishing_park = FishingPark.find(params[:fishing_park_id])
  end
end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
   before_action :authenticate_user!

#   def index
#   end
end

app/controllers/fishing_parks_controller.rb
class FishingParksController < ApplicationController
  before_action :authenticate_user!

  def fish
    # @fishing_park = FishingPark.find(params[:id])
    #@fishing_parks = FishingPark.all
    # @fishing_parks = FishingPark.page(params[:page]).per(5)
  end

  def rank
    #番号の多い順に並び替え、表示する最大数を8個に指定する。最後にpluckでfishing_park_idカラムのみを数字で取り出すように指定。
    @all_ranks = FishingPark.find(Favorite.group(:fishing_park_id).order('count(fishing_park_id) desc').limit(8).pluck(:fishing_park_id))
  end

  def search
    @word = params[:search_word]
    @fishing_parks = FishingPark.search(@word)
  end


  def new
    @fishing_park = FishingPark.new
  end

  def create
    @fishing_park = FishingPark.new(fishing_park_params)
    @fishing_park.save!
    redirect_to fishing_parks_path
  end

  def index
    #@fishing_parks = FishingPark.all
    @fishing_park = FishingPark.new
    # kaminariでページ機能をつけるための記述
    @fishing_parks = FishingPark.page(params[:page]).per(4)
  end

  def show
    @fishing_park = FishingPark.find(params[:id])
    @review = Review.new
    @reviews = @fishing_park.reviews.page(params[:page]).per(2)
  end

  def edit
    @fishing_park = FishingPark.find(params[:id])
  end

  def update
    @fishing_park = FishingPark.find(params[:id])
    if @fishing_park.update(fishing_park_params)
      redirect_to fishing_parks_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    # @fishing_park = FishingPark.user
    @fishing_park = FishingPark.find(params[:id])
    @fishing_park.destroy!
    redirect_to fishing_parks_path
  end

end

  private
  def fishing_park_params
    params.require(:fishing_park).permit(:name, :address, :fishing_fee, :fishing_children_fee, :image, :map_image, :tour_fee, :children_tour_fee, :body, :fish_body, :map_body)
  end

  # def user_admin
  #   @fishing_park = FishingPark.find(params[:id])
  #   if  current_user.admin == false
  #     redirect_to root_path
  #   else
  #       render action: "index"
  #   end
  # end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    # 送られてきた情報を格納する
    @review.user_id = current_user.id
    if @review.save
      redirect_to fishing_park_path(@review.fishing_park)
    else
      # renderはアクションを返さないため変数が足りているかを確認する
      @fishing_park = FishingPark.find(params[:fishing_park_id])
      #@fishing_park = FishingPark.find(params[:id]
      @reviews = @fishing_park.reviews.page(params[:page]).per(2)
      render "fishing_parks/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy!
    redirect_to fishing_park_path(@review.fishing_park)
  end

  private
  def review_params
    # viewから送られてくるのがfishing_parkのためuser_idは記述しない
    params.require(:review).permit(:fishing_park_id, :content, :score)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/fishes_helper.rb
module FishesHelper
end

app/helpers/fishing_parks_helper.rb
module FishingParksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$("#favorite_<%= @fishing_park.id %>").html("<%= j(render partial: 'fishing_parks/favorite', locals: {fishing_park: @fishing_park}) %>");

app/views/favorites/destroy.js.erb
$("#favorite_<%= @fishing_park.id %>").html("<%= j(render partial: 'fishing_parks/favorite', locals: {fishing_park: @fishing_park}) %>");

app/views/fishing_parks/_favorite.html.erb
  <% if current_user.favorited_by?(fishing_park.id) %>
  <!--remote: trueでJavascriptを呼び出す-->
    <span>いいね</span>
    <%= link_to '', favorites_path(fishing_park_id: fishing_park.id), method: :delete, class: "glyphicon glyphicon-heart", remote: true %>
    <%= fishing_park.favorites.count%>
  <% else %>
    <span>いいね</span>
    <%= link_to '', favorites_path(fishing_park_id: fishing_park.id), method: :post, class: "glyphicon glyphicon-heart-empty", remote: true %>
    <%= fishing_park.favorites.count%>
  <% end %>

app/views/fishing_parks/edit.html.erb
  <div class="text-center"><br><br><br><br>
   <h1>No Message</h1>
  </div>
  <div class="container">
    <!--海釣り公園の情報を変更する内容-->
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= form_with model: @fishing_park, local:true do |f| %>
          <label>image</label><br>
            <p><%= f.attachment_field :image %></p>
          <label>address</label>
            <p><%= f.text_field :address %></p>
          <label>name</label>
            <p><%= f.text_field :name %></p>
           <label>fishing_fee</label>
            <p><%= f.text_field :fishing_fee %></p>
          <label>fishing_children_fee</label>
            <p><%= f.text_field :fishing_children_fee %></p>
          <label>tour_fee</label>
            <p><%= f.text_field :tour_fee %></p>
          <label>children_tour_fee</label>
            <p><%= f.text_field :children_tour_fee %></p>
          <label>サイトURL</label>
            <p><%= f.text_field :body %></p>
          <label>Map:URL</label>
            <p><%= f.text_field :map_body %></p>
          <label>Map:image</label><br>
            <p><%= f.attachment_field :map_image %></p>
          <%= f.submit 'Update' %>
        <% end %>
      <% end %>
    <% end %>
  </div>

app/views/fishing_parks/fish.html.erb
  <div class="col-xs-1"></div>
    <div class="col-xs-11">
      <h1>主に釣れる魚概要</h1>
      <h3><%= link_to '魚の概要サイトはこちらへ',"https://fishai.jp/", target: :_blank %></h3>
      <table class="table">
        <thead>
          <tr>
            <th class="table-head"><h3>魚の名前</h3></th>
            <th>
              <h3>概要</h3>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><h3><strong>メバル</strong></h3></th>
            <th><h3>浅場の岩礁域や海藻の茂る場所を好み、1年中釣れるが主に<strong>11月～4月</strong>がよく釣れる。</th>
          </tr>
          <tr>
            <th><h3><strong>チヌ</strong></h3></th>
            <th><h3>チヌとは、通称クロダイと呼ばれている。日本列島の幅広い区域に生息しており、1年中狙うことのできる魚種。旬は、基本的に<strong>５月～１０月</strong>。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>ガシラ</strong></h3></th>
            <th><h3>通称カサゴ。カサゴは関西とか四国では、カサゴ（ガシラ）と呼ぶ。ガシラは根掛かりがしやすい堤防や磯まわりなどの岩礁帯に棲息している。1年中釣れるが主に<strong>4月～9月</strong>がよく釣れる。</h3></th>
          </tr>
            <th><h3><strong>アイナメ</strong></h3></th>
            <th><h3>岩礁帯の底付近を好み、岩などの隙間に生息している。アイナメの釣れる時期は、アイナメの適水温は8～15°Cとされているため、<strong>11月～４月の晩秋から初春の寒い時期</strong>。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>カレイ</strong></h3></th>
            <th><h3>カレイは1年中狙うことができるが、基本的には<strong>11月中旬～4月ごろ</strong>。カレイの産卵期は1～2月のためあまり釣れず、産卵後3～4月はよく釣れます。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>グレ</strong></h3></th>
            <th><h3>通称メジナ。関西圏や九州ではグレと呼ばれる。メジナ（グレ）の産卵は３月～５月のため、あまり釣れず、梅雨に入ると活発に活動するので、<strong>梅雨の時期</strong>によく釣れる。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>ハゲ</strong></h3></th>
            <th><h3>通称カワハギ。関西圏や中国地方ではハゲと呼ばれる。カワハギ（はげ）1年中狙うことができるが、<strong>5月～9月</strong>、<strong>11月〜2月</strong>と2回の旬がある。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>アジ</strong></h3></th>
            <th><h3>基本的には1年中釣れるが、主に<strong>6月～12月頃</strong>釣れる。アジは群れで行動する習性があるため、一度釣れるとアジの群れがいることがわかる。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>サバ</strong></h3></th>
            <th><h3>4月〜12月まで釣れますが、主に<strong>9月~10月</strong>がよく釣れる。9月～10月では大物が釣れやすくなるため、手ごたえのある釣りになる。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>ハマチ</strong></h3></th>
            <th><h3>ハマチは出世魚（しゅっせうお）とも呼ばれ、大きくなるにつれて、モジャコ（ワカナゴ）→ツバス→ハマチ→メジロ（オオイオ）→ブリとなる。ハマチは西での呼び名になる。ハマチは、4月～12月に釣ることができ、主に<strong>7月～11月</strong>がよく釣れる。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>スズキ</strong></h3></th>
            <th><h3>スズキは出世魚（しゅっせうお）とも呼ばれ、大きくなるにつれて、コッパ→セイゴ→フッコ→スズキとなる。1年中狙える魚ですが、ベストシーズンは<strong>秋から初冬</strong>。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>タイ</strong></h3></th>
            <th><h3>あまり広範囲を動き回らず、海底の根周りを中心に、水深10～100mの岩礁帯や砂礫底の場所に生息している。基本的には1年中釣れるが、主に<strong>春から晩秋</strong>にかけて釣れる。</h3></th>
          </tr>
          <tr>
            <th><h3><strong>イシダイ</strong></h3></th>
            <th><h3>沿岸部の岩礁域や岩の隙間などに潜み、海底付近に生息している。水温が１８～２４°Cで活発に活動するため、主に<strong>春と秋4～11月ごろ</strong>が釣りのシーズン。</h3></th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

app/views/fishing_parks/index.html.erb
  <div class="container">
    <h1>海釣り公園一覧</h1>
    <div class="text-center">
      <% @fishing_parks.each do |fishing_park| %>
        <div class="row">
          <%= link_to fishing_park_path(fishing_park.id) do %>
            <div class="col-md-3">
              <%= attachment_image_tag fishing_park, :image, size:'180x180' %>
            </div>
            <div class="col-md-5">
              <div style="height: 40px;">
                <p>名称 ： <%= fishing_park.name %></p>
              </div>
              <div style="height: 40px;">
                <p>住所 ： <%= fishing_park.address %></p>
              </div>
              <div style="height: 50px;">
                <h4>料金</h4>
                <p><%= fishing_park.fishing_fee %></p>
              </div>
              <div style="height: 50px;"><br>
                <p><%= fishing_park.fishing_children_fee %></p>
              </div>
            </div>
            <div class="col-md-4">
              <div style="height: 40px;">
                <h4>入園料(見学の人)</h4>
                <p><%= fishing_park.tour_fee %></p>
                <p><%= fishing_park.children_tour_fee %></p>
              </div>
            </div>
          <% end %><br><br><br><br><br>
  
          <!--renderでいいね機能を部分テンプレート-->
          <div id="favorite_<%= fishing_park.id %>">
             <%= render partial: 'favorite', locals: { fishing_park: fishing_park} %>
          </div>
  
          <% if user_signed_in? %><br><br>
            <% if current_user.admin? %>
              <%= link_to "編集", edit_fishing_park_path(fishing_park.id) %>
              <%= link_to "削除する", fishing_park_path(fishing_park.id), method: :delete, "data-confirm" => "削除しますか？" %>
            <% end %>
          <% end %>
        </div>
        <hr>
      <% end %>
      <!---ページング機能-->
        <%= paginate @fishing_parks %>
    </div>
  </div>

  <div class="container"><br>
  <!--管理者のみ投稿を表示させる記述-->
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= form_with model: @fishing_park, local:true do |f| %>
          <label>image</label>
            <p><%= f.attachment_field :image %></p>
          <label>address</label>
            <p><%= f.text_field :address %></p>
          <label>name</label>
            <p><%= f.text_field :name %></p>
           <label>fishing_fee</label>
            <p><%= f.text_field :fishing_fee %></p>
          <label>fishing_children_fee</label>
            <p><%= f.text_field :fishing_children_fee %></p>
          <label>tour_fee</label>
            <p><%= f.text_field :tour_fee %></p>
          <label>children_tour_fee</label>
            <p><%= f.text_field :children_tour_fee %></p>
          <label>サイトURL</label>
            <p><%= f.text_field :body %></p>
          <label>Map:URL</label>
            <p><%= f.text_field :map_body %></p>
          <label>Map:image</label>
            <p><%= f.attachment_field :map_image %></p>
          <%= f.submit 'Create' %>
        <% end %>
     <% end %>
    <% end %>
  </div>

app/views/fishing_parks/rank.html.erb
  <div class="container">
    <h1>いいね多いランキング</h1><br>
    <div class="text-center">
      <% @all_ranks.each do |fishing_park| %>
        <div class="row">
          <%= link_to fishing_park_path(fishing_park.id) do %>
            <div class="col-md-3">
              <%= attachment_image_tag fishing_park, :image, size:'180x180' %>
            </div>
            <div class="col-md-5">
              <div style="height: 40px;">
                <p>名称 ： <%= fishing_park.name %></p>
              </div>
              <div style="height: 40px;">
                <p>住所 ： <%= fishing_park.address %></p>
              </div>
              <div style="height: 60px;">
                <h4>料金</h4>
                <p><%= fishing_park.fishing_fee %></p>
              </div>
              <div style="height: 50px;">
                <p><%= fishing_park.fishing_children_fee %></p>
              </div>
            </div>
            <div class="col-md-4">
              <div style="height: 50px;">
                <h4>入園料(見学の人)</h4>
                <p><%= fishing_park.tour_fee %></p>
                <p><%= fishing_park.children_tour_fee %></p>
              </div>
            </div>
          <% end %><br><br><br><br><br><br><br>

          <div id="favorite_<%= fishing_park.id %>">
             <%= render partial: 'fishing_parks/favorite', locals: { fishing_park: fishing_park} %>
          </div>

          <% if user_signed_in? %>
            <% if current_user.admin? %><br>
              <%= link_to "編集", edit_fishing_park_path(fishing_park.id) %>
              <%= link_to "削除する", fishing_park_path(fishing_park.id), method: :delete, "data-confirm" => "削除しますか？" %>
            <% end %>
          <% end %>
        </div>
        <hr>
      <% end %>
    </div>
  </div>

app/views/fishing_parks/search.html.erb
  <div class="container">
    <h1>海釣り公園検索結果</h1><br>
    <div class="text-center">
      <% @fishing_parks.each do |fishing_park| %>
        <div class="row">
          <%= link_to fishing_park_path(fishing_park.id) do %>
            <div class="col-md-3">
              <%= attachment_image_tag fishing_park, :image, size:'180x180' %>
            </div>
            <div class="col-md-5">
              <div style="height: 40px;">
                <p>名称 ： <%= fishing_park.name %></p>
              </div>
              <div style="height: 40px;">
                <p>住所 ： <%= fishing_park.address %></p>
              </div>
              <div style="height: 50px;">
                <h4>料金</h4>
                <p><%= fishing_park.fishing_fee %></p>
              </div>
              <div style="height: 50px;"><br>
                <p><%= fishing_park.fishing_children_fee %></p>
              </div>
            </div>
            <div class="col-md-4">
              <div style="height: 40px;">
                <h4>入園料(見学の人)</h4>
                <p><%= fishing_park.tour_fee %></p>
                <p><%= fishing_park.children_tour_fee %></p>
              </div>
            </div>
          <% end %><br><br><br><br><br>
  
          <!--renderでいいね機能を部分テンプレート-->
          <div id="favorite_<%= fishing_park.id %>">
             <%= render partial: 'favorite', locals: { fishing_park: fishing_park} %>
          </div>
  
          <% if user_signed_in? %>
            <% if current_user.admin? %><br><br><br>
              <%= link_to "編集", edit_fishing_park_path(fishing_park.id) %>
              <%= link_to "削除する", fishing_park_path(fishing_park.id), method: :delete, "data-confirm" => "削除しますか？" %>
            <% end %>
          <% end %>
        </div>
        <hr>
      <% end %>
    </div>
  </div>

app/views/fishing_parks/show.html.erb
  <!--indexの情報を@fishing_parkでもってくる-->
  <div class="container-fluid">
  	<div class="row">
  		<div class="col-xs-12 col-md-4" >
        <div class='text-center'>
          <%= attachment_image_tag @fishing_park, :image, size:'260x260' %>
          <!--renderでいいね機能を部分テンプレート-->
          <div id="favorite_<%= @fishing_park.id %>">
            <%= render partial: 'fishing_parks/favorite', locals: { fishing_park: @fishing_park} %>
          </div>
          <hr>
        </div>
  		</div>
  		<div class="col-xs-12 col-md-8">

    		<div class="col-md-6 text-center">
          <h1><%= @fishing_park.name %></h1>
          <p>名称 ： <%= @fishing_park.name %></p>
          <hr>
          <p>住所 ： <%= @fishing_park.address %></p>
          <hr>
          <p>料金</p>
          <p><%= @fishing_park.fishing_fee %></p>
          <p><%= @fishing_park.fishing_children_fee %></p>
          <hr>
          <p>入園料(見学の人)</p>
          <p><%= @fishing_park.tour_fee %></p>
          <p><%= @fishing_park.children_tour_fee %></p>
          <hr>
          <p><%= link_to 'この海釣り公園のホームページへ', @fishing_park.body, target: :_blank %></p>
          <hr>
        </div>
      </div>
    </div>
    <%= render 'reviews/form', review: @review, fishing_park: @fishing_park %>

    <div class="col-xs-12 col-md-12 text-center">
      <label><h2>地図</h2></label>
      <hr>
      <h2><%= link_to 'この地図のGoogleMapへ', @fishing_park.map_body, target: :_blank %></h2>
      <hr>
      <p><%= attachment_image_tag @fishing_park, :map_image %></p>
    </div>
  </div>

app/views/home/about.html.erb
  <div class="text-center"><br><br><br><br><br><br>
    <h1><strong>About</strong></h1><br><br>
      <p>釣りが好きな方や、初めて釣りをする人に向けたサイトです。</p>
      <p>近畿地方だけになりますが</p>
      <p>お気に入りの海釣り公園や行ってみたいと思う海釣り公園を</p>
      <p>見つけてもらえるようにまとめて掲載しており</p>
      <p>少しでも釣りに興味を持っていただければと思い、このサイトを作りました。</p>
      <p>皆さんのお役に立てれば幸いです。</p>
  </div>

app/views/home/top.html.erb
  <div class="text-center"><br><br><br><br><br><br>
    <h1><strong>ようこそ！ <p>Fishing&fishサイトへ！</strong></p></h1><br><br>
      <p>近畿の海釣り公園に特化し</p>
      <p>釣りをする人やこれから釣りをしたい人が</p>
      <p>どこで釣りをするかを探すサイトです。</p>
      <p>使用するには、新規登録を行う必要があります。
  </div>

app/views/reviews/_form.html.erb
  <div class="col-xs-12 col-md-6">
  <p>レビューを書く</p>

    <% if @review.errors.any? %>
      <div class="notification is-danger">
        <h2><%= @review.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="rating-box">
      <%= form_with model: @review, url: fishing_park_reviews_path(@fishing_park), local: true do |f| %>
      <span>評価</span>
        <div class="ratings">
          <!--星をつけ0~5個で評価する-->
          <span class="fa fa-star-o" id="star"></span>
          <span class="fa fa-star-o" id="star"></span>
          <span class="fa fa-star-o" id="star"></span>
          <span class="fa fa-star-o" id="star"></span>
          <span class="fa fa-star-o" id="star"></span>
        </div>
         <!--星が5個あるためわかりやすく表示-->
        <div class="rating-value-display"><span id="rating-value-display">0</span>/5</div>
        <!--どの海釣り公園に結び付けられているレビューかを記述-->
        <%= f.hidden_field :fishing_park_id, value: @fishing_park.id %>
        <%= f.hidden_field :score, id: "rating-value" %>
        <div class="1">
          <%= f.text_area :content, size: "30x5", class: "form-control" %>
        </div>
        <p><%= f.submit "保存", class: "button mt-3 btn btn-primary" %></p>
      <% end %>
    </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <% @reviews.each do |review| %>
      <div style ='margin-bottom:20px'>
        <div class='row'>
          <hr>
          <div class='col-xs-3'>評価</div>
          <div class='col-xs-9'>
            <% review.score.times do %>
              <span class="fa fa-star-o" id="star"></span>
            <% end %>
          </div>
        </div><hr>
        <div class="row">
          <div class="col-xs-3">内容</div>
          <div class="review_content col-xs-9"><%= review.content %></div>
        </div><hr>
        <div class="row">
          <div class="col-xs-12">
             <%= link_to "削除", fishing_park_review_path(@fishing_park.id,review), method: :delete, "data-confirm" => "削除しますか？", class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>

    <%= paginate @reviews %>
  </div>

  <%= javascript_include_tag 'reviews.js' %>

app/views/users/edit.html.erb
 <div class="container">
    <% if @user.errors.any? %>
      <div class="notification is-danger">
        <h2><%= @user.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-xs-3">
      <h2>マイページ編集</h2>
      <h3>登録情報</h3>
      <%= form_with model: @user, local:true do |f| %>
        <table class="table table-bordered">
          <%= f.label :名前 %><br>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %><br><br>
          <%= f.label :メールアドレス %><br>
          <%= f.text_field :email, autofocus: true, autocomplete: "email" %><br><br>
          <%= f.submit '変更完了', class: "btn btn-primary" %>
        </table>
      <% end %>
    </div>
  </div>

app/views/users/quit.html.erb
  <div class="text-center"><br><br><br><br><br><br><br><br>
    <h3><strong>本当に退会しますか</strong></h3>
    <p>退会すると、会員登録情報の削除や</p>
    <p>当サイトが利用できなくなってしまいます。</p>
    <p>退会する場合は、「退会する」をクリックしてください。</p>
    <%= link_to "退会しない", user_path(current_user), class: 'btn btn-primary' %>
    <%= link_to "退会する", user_path(current_user), method: :delete, "data-confirm" => "本当に退会しますか？", class: 'btn btn-danger' %>
  </div>

app/views/users/show.html.erb
  <div class="container">
    <div class="col-xs-8"><br>
      <h2>マイページ</h2><br><br>
      <h3>登録情報</h3>
      <table class="table table-bordered">
        <tr>
          <th>氏名</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <th><%= @user.email %></th>
           </tr>
      </table>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
        <% else %>
          <th><%= link_to "User編集", edit_user_path, class: 'btn btn-primary' %></th>
          <th><%= link_to "退会ヘ進む", quit_path, class: 'btn btn-danger' %></th>
        <% end %>
      <% end %>
    </div>
  </div>