config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#top'
  get '/home/about' => 'home#about', as: 'about'
  get '/users/quit' => 'users#quit', as: 'quit'
  get '/fish' => 'fishing_parks#fish'


  resources :fishing_parks do
    get :fish, on: :member
    get :rank, on: :collection
    get :search, on: :collection
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :destroy, :update]
  resource :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_park
  
  validates_uniqueness_of :fishing_park_id, scope: :user_id
  
end

app/models/fishing_park.rb
class FishingPark < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy

  has_many :reviews, dependent: :destroy


  attachment :image
  attachment :map_image


  def self.search(word)
    # return FishingPark.all unless search
    FishingPark.where(['name LIKE ?', "%#{word}%"])
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_park
  
  # 評価を必須にする
  validates :score, presence: true
  validates :content, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :fishing_parks, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

  def favorited_by?(fishing_park_id)
   favorites.where(fishing_park_id: fishing_park_id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    fishing_parks_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])

    devise_parameter_sanitizer.permit(:account_update,keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_fishing

  def create
    @favorite = Favorite.create(user_id: current_user.id, fishing_park_id: params[:fishing_park_id])
    # 非同期通信を行うためコメントアウト
    # redirect_to fishing_park_path(params[:fishing_park_id])
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, fishing_park_id: params[:fishing_park_id])
    @favorite.destroy
    # 非同期通信を行うためコメントアウト
    # redirect_to fishing_park_path(params[:fishing_park_id])
  end

  private
  def set_fishing
    @fishing_park = FishingPark.find(params[:fishing_park_id])
  end
end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
   before_action :authenticate_user!

#   def index
#   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    # 送られてきた情報を格納する
    @review.user_id = current_user.id
    if @review.save
      redirect_to fishing_park_path(@review.fishing_park)
    else
      # renderはアクションを返さないため変数が足りているかを確認する
      @fishing_park = FishingPark.find(params[:fishing_park_id])
      #@fishing_park = FishingPark.find(params[:id]
      @reviews = @fishing_park.reviews.page(params[:page]).per(2)
      render "fishing_parks/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy!
    redirect_to fishing_park_path(@review.fishing_park)
  end

  private
  def review_params
    # viewから送られてくるのがfishing_parkのためuser_idは記述しない
    params.require(:review).permit(:fishing_park_id, :content, :score)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/fishes_helper.rb
module FishesHelper
end

app/helpers/fishing_parks_helper.rb
module FishingParksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
  <header class="navbar navbar-dark" style="background-color:#00d5ff;">
    <div class="container">
      <nav class="spmenu navbar navbar-expand-md navbar-dark bg-dark d-flex justify-content-between">
        <ul class="pull-left">
          <%= image_tag"logo (1).png", size: "120x90" %>
        </ul>
        <ul class="pull-right">
          <button  type="button" data-toggle="modal" data-target="#menuModal" aria-label="Toggle navigation">
            <%= image_tag 'Hamburger.png', style: "width: 30px; height: 30px;" %>
          </button>
        </ul>
      </nav>
      <div class="modal fade fullscreen" id="menuModal"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title">メニュー</h5>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
             <span aria-hidden="true"></span>
           </button>
          </div>
          <div class="modal-body">
            <ul style="list-style-type:none;">
              <% if user_signed_in? %>
                <li><%= link_to 'マイページ', user_path(current_user), class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to '釣り一覧', fishing_parks_path, class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to '魚一覧', fish_fishing_park_path(current_user), class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to 'ランキング', rank_fishing_parks_path(current_user), class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
              <% else %>
                <li><%= link_to 'About', about_path, class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to 'Top', root_path, class: "btn btn-default navbar-btn" %></li>
                <li><%= link_to '新規登録', new_user_registration_path, class: "btn btn-default navbar-btn"%></li>
                <li><%= link_to 'ログイン', new_user_session_path, class: "btn btn-default navbar-btn"%></li>
              <% end %>

              <% if user_signed_in? %>
                <%= form_with url: search_fishing_parks_path, method: :get, local: true do |f| %>
                  <%= text_field_tag :search_word %>
                  <%= submit_tag '検索', :name => nil %>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <nav class="pcmenu">
        <ul class="nav navbar-nav navbar-left">
          <%= image_tag"logo (1).png", size: "240x90" %>
        </ul>
      　<ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'マイページ', user_path(current_user), class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to '釣り一覧', fishing_parks_path, class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to '魚一覧', fish_path, class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to 'ランキング', rank_fishing_parks_path(current_user), class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
          <% else %>
            <li><%= link_to 'About', about_path, class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to 'Top', root_path, class: "btn btn-default navbar-btn" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "btn btn-default navbar-btn"%></li>
            <li><%= link_to 'ログイン', new_user_session_path, class: "btn btn-default navbar-btn"%></li>
          <% end %>

          <% if user_signed_in? %>
            <%= form_with url: search_fishing_parks_path, method: :get, local: true do |f| %>
              <%= text_field_tag :search_word %>
              <%= submit_tag '検索', :name => nil %>
            <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--width=device-widthで、横幅をデバイスのサイズに合わせる、initial-scale=1は、倍率を指定する、shrink-to-fit=noは、iOS9でViewが崩れても、正常に表示できるようにする。-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FishingFish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--星の画像をつけるために使用-->
    <script src="https://kit.fontawesome.com/838216ec5f.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>